### ISSUE TITLE
where is the "resource/empty.png"

### ISSUE THREAD

**Issue by VinsonXuxuxu** [rahmatnazali/pimage#1]
for help:where is the "resource/empty.png"

**Comment by rnazali** [comment]
It is just a square black image to be used as a ground-truth for non tempered image, if i am not mistaken.
It just really a totally black (255, 255, 255) image, having exactly same resolution as the input image.
You can manually create it using Paint/GIMP or so.

I remove it from the project on purpose for the brievity.
