### ISSUE TITLE
What to do next after creating a virtual env. & installing packages from requirement.txt?

### ISSUE THREAD

**Issue by NadisSadikFahim** [rahmatnazali/pimage#12]
I am pretty new to the python world & I have been able to successfully create virtual environment & installing packages from requirement.txt. But I can't figure out what to do next to run your code. Please help me out with the situation. I couldn't understand from the "Example".

**Comment by rnazali** [comment]
Just create a python file, say `example.py` on the root directory of the project (i.e. same directory witth the folder `copy_move_detection`.

Inside the `example.py` , paste the example code:

```
from copy_move_detection import detect
detect.detect('assets/', 'dataset_example_blur.png', 'output/', block_size=32)
```

Then insert your image (to be detected) inside `assets` folder.

Simply change the parameter of the code, say change the `dataset_example_blur.png` to `your_image.png`.

Finally, run the python script **inside your venv** :

```
python3 example.py
```
