### ISSUE TITLE
help about output

### ISSUE THREAD

**Issue by yanmengdi123** [rahmatnazali/pimage#14]
hi,I used your example diagram for testing, but I copied and pasted it myself, again with blank results.
The way I do it is just regular copy and paste.
I wonder why?
Thank you very much!

**Comment by yanmengdi123** [comment]
![20210513_163835_lined_dataset_example](https://user-images.githubusercontent.com/57667099/118101032-bb005a80-b409-11eb-8e3b-178b9971e941.png)
![20210513_163835_dataset_example](https://user-images.githubusercontent.com/57667099/118101051-bf2c7800-b409-11eb-8b59-ac823e7ac1ad.png)

**Comment by pankaiqianghub** [comment]
我也是这个问题，请问你知道怎么解决了吗

**Comment by rnazali** [comment]
It seems to me that you used a relatively smaller copy pasted region. Try to use smaller block size. The default value was 32 if I wasn't mistaken. Try 16 or lower, it may increase the running time but generally will hold better result.

If you prefer to keep the parameter as it is, try to increase your copy pasted region (i.e. select bigger image region that you use for the attack)
