### ISSUE TITLE
Not able to fetch and get the output 

### ISSUE THREAD

**Issue by ajeet1807** [rahmatnazali/pimage#16]
**ERROR SHOWN-**

C:\Users\alman\anaconda3\python.exe E:/image-copy-move-detection-python2-master/main_GUI.py
E:/image-copy-move-detection-python2-master/screenshot/horse_blur.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\alman\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\image-copy-move-detection-python2-master\main_GUI.py", line 91, in onFilePicker
    imageRight = Image.open("../testcase_result/")
  File "C:\Users\alman\anaconda3\lib\site-packages\PIL\Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: '../testcase_result/'
horse_blur.png
Step 1 of 4: Object and variable initialization
Exception in Tkinter callback
<ImageObject.ImageObject object at 0x000001A22EC54B80>
Traceback (most recent call last):
  File "C:\Users\alman\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\image-copy-move-detection-python2-master\main_GUI.py", line 109, in onDetect
    imageResultPath = CopyMoveDetection.detect(self.imagePath, self.imageName, '../testcase_result/', blockSize=32)
  File "E:\image-copy-move-detection-python2-master\CopyMoveDetection.py", line 56, in detect
    singleImage = ImageObject.ImageObject(sourceDirectory, fileName, blockSize, outputDirectory)
  File "E:\image-copy-move-detection-python2-master\ImageObject.py", line 71, in __init__
    print (self).Nb, self.isThisRGBImage
AttributeError: 'NoneType' object has no attribute 'Nb'

**Comment by rnazali** [comment]
The GUI (with tkinter) is not being supported yet on this version project. Please use the one without GUI.

**Comment by ajeet1807** [comment]
I am trying to run the old repo of the GUI supported version these are the problems showing for the same.

**Comment by rnazali** [comment]
Yes, because GUI is not being supported anymore. The old repo is never being maintained again.

What you can do is to first make sure you can run the script only (no GUI). If the code works, then you may try to implement the GUI by yourself.

The purpose of this repo is to demonstrate how we can find a copy move fraud inside a digital image. With or without GUI does not really matter.

**Comment by ajeet1807** [comment]
I had also tried to run the without GUI version but it is also showing some
error. Do you have time to help in configuring the errors of the project on
google meet or something?

**Comment by rnazali** [comment]
What error do you have when running the script version?

No, I don't think e-meet is an appropriate solution for this. Sorry you have to figure it for yourself.

**Comment by ajeet1807** [comment]
Can you help me run the GUI version of the project? There are few errors
only, I need it to run as soon as possible. It's an emergency. I need to
submit this within a very short time soon.

Thanks & Regards,
Ajeet

**Comment by rnazali** [comment]
As I have said before, this project no longer cover the GUI implementation.
I'm also no longer actively working with python GUI on my daily work so honestly I won't be able to help you even if I want to.

I can only hope for your good luck.
