### ISSUE TITLE
I am getting the result but i am getting blank images can you help me with it.

### ISSUE THREAD

**Issue by pran437** [rahmatnazali/pimage#4]

**Comment by pran437** [comment]
@studiawan  can you look into the issue?

**Comment by rnazali** [comment]
It can be one of these cases:
- Your image are original. Hence no fraud, and the result will be blank.
- Your image contains a fraud, but the fraud are too small compared to the _blockSize_, so the alternatives for this point are:
  - reduce your _blockSize_
  - You need to have a bigger resolution of the images

I designed this script for a specific limitation of images and fraud type (i.e. a certain minimum resolution of the image and fraud size must be fulfilled). I can not guarantee that this script will be able to detect fraud from a random images that did not met the limitation.

**Comment by pran437** [comment]
> 
> 
> It can be one of these cases:
> 
>     * Your image are original. Hence no fraud, and the result will be blank.
> 
>     * Your image contains a fraud, but the fraud are too small compared to the _blockSize_, so the alternatives for this point are:
>       
>       * reduce your _blockSize_
>       * You need to have a bigger resolution of the images
> 
> 
> I designed this script for a specific limitation of images and fraud type (i.e. a certain minimum resolution of the image and fraud size must be fulfilled). I can not guarantee that this script will be able to detect fraud from a random images that did not met the limitation.
![horse_blur](https://user-images.githubusercontent.com/33084295/54800377-8bb98d00-4c87-11e9-9141-22d8a136ad2d.png)

i have used the above mentioned image itself even though i am getting it blank only one thing i have changed _builtin not working so i used builtins can you look into it please. Thanks in advance.

**Comment by rnazali** [comment]
> i have used the above mentioned image itself even though i am getting it blank only one thing i have changed _builtin not working so i used __builtin_ can you look into it please. Thanks in advance.

Can you tell me which line and file you edit? Let me try to reproduce your case.
Can you tell me what version of Python are you using?
Also can you post what the console prints?

**Comment by pran437** [comment]
I am using python 3.5.2
 for key in sorted(self.offsetDictionary, key=lambda key: builtins.len(self.offsetDictionary[key]),
                          reverse=True):
this line is in image reconstruction part instead of _builtin_ i used builtins as i said this belongs to ImageObject.py
yes sure i will send it can you please mention the block size you preffered

**Comment by rnazali** [comment]
you could try 16 or 32 as the _blockSize_. The smaller the value the more accurate it will get, but it will surely took more time to finish.

You said the script finished but detecting no fraud. So I think this is a matter of configuration rather than a coding error.

Let me know if any error popped up.

**Comment by pran437** [comment]
i will share you the whole output console and the code files then that would help to debug.

**Comment by pran437** [comment]
![Capture](https://user-images.githubusercontent.com/33084295/55019709-69bf6200-501b-11e9-95b0-fc4232ebdb84.PNG)
![Capture2](https://user-images.githubusercontent.com/33084295/55019742-75ab2400-501b-11e9-83eb-90dafe544107.PNG)
this is what comes in the console i didn't attach some similar output of step 2
and the array at the ending is the groundtruthbox

**Comment by pran437** [comment]
Is the output console same just i added few print statements to know the values of variables, remaining code is the same and i took block size as 16.

**Comment by pran437** [comment]
these are output images 
![20190401_214815_horse_blur](https://user-images.githubusercontent.com/33084295/55343115-0d9b8880-54c8-11e9-92b0-a5152e376312.png)
![20190401_214815_lined_horse_blur](https://user-images.githubusercontent.com/33084295/55343116-0d9b8880-54c8-11e9-8b38-c091b6106345.png)

**Comment by yanmengdi123** [comment]
> these are output images
> ![20190401_214815_horse_blur](https://user-images.githubusercontent.com/33084295/55343115-0d9b8880-54c8-11e9-92b0-a5152e376312.png)
> ![20190401_214815_lined_horse_blur](https://user-images.githubusercontent.com/33084295/55343116-0d9b8880-54c8-11e9-8b38-c091b6106345.png)

Have you solved your problem？
