### ISSUE TITLE
Implementation of GUI for Py 3.x

### ISSUE THREAD

**Issue by mrrobot223** [rahmatnazali/pimage#8]
Im trying to implement the GUI for the new repo with the help of your old repo, but im getting an error. Below is the error what im getting now. can you please help me fix it. And ill attach the GUI code and the detect.py code to this.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\shuch\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "D:/image-copy-move-detection-master/copy_move_detection/Main1.py", line 96, in onDetect
    imageResultPath = detect.detect(self.imagePath, self.imageName, '../output/', block_size=32)
TypeError: detect() got multiple values for argument 'block_size' 

[copy_move_detection.zip](https://github.com/rahmatnazali/image-copy-move-detection/files/4541217/copy_move_detection.zip)

**Comment by rnazali** [comment]
the error suggested that you pass a multiple values for argument `block_size`, usually something like tuple, string, or list.
But I found your Main1.py did call the function in correct way.

At a slight, IDK what is the problem.

**Comment by mrrobot223** [comment]
[Main_GUI.zip](https://github.com/rahmatnazali/image-copy-move-detection/files/4551226/Main_GUI.zip)

I have fixed the issue with the GUI. you can upload it in your repository. so that others can use if they need it.

**Comment by rnazali** [comment]
Thanks, I will look into it.
